Ensemble Learning (Any one)
A. Implement Random Forest Classifier model to predict the safety of the car.
Dataset link: https://www.kaggle.com/datasets/elikplim/car-evaluation-data-set

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [2]:
# Load the dataset
data = pd.read_csv("Car_Evaluation.csv", header=None)
data

          0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [7]:
# Add column names based on your description
columns = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "class"]
data.columns = columns
data

     buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [11]:
# Convert categorical features to numerical using one-hot encoding
data_encoded = pd.get_dummies(data, columns=columns[:-1], drop_first=True)
data_encoded

,class,buying_low,buying_med,buying_vhigh,maint_low,maint_med,maint_vhigh,doors_3,doors_4,doors_5more,persons_4,persons_more,lug_boot_med,lug_boot_small,safety_low,safety_med
0,unacc,False,False,True,False,False,True,False,False,False,False,False,False,True,True,False
1,unacc,False,False,True,False,False,True,False,False,False,False,False,False,True,False,True
2,unacc,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False
3,unacc,False,False,True,False,False,True,False,False,False,False,False,True,False,True,False
4,unacc,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,good,True,False,False,True,False,False,False,False,True,False,True,True,False,False,True
1724,vgood,True,False,False,True,False,False,False,False,True,False,True,True,False,False,False
1725,unacc,True,False,False,True,False,False,False,False,True,False,True,False,False,True,False
1726,good,True,False,False,True,False,False,False,False,True,False,True,False,False,False,True
1727,vgood,True,False,False,True,False,False,False,False,True,False,True,False,False,False,False

In [13]:
# Split data into input features (X) and target labels (y)
X = data_encoded.drop('class', axis=1)  # 'class_unacc' is one of the target classes
y = data_encoded['class']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Create the Random Forest Classifier model
rf_classifier = RandomForestClassifier(random_state=42)

# Train the model
rf_classifier.fit(X_train, y_train)

In [3]:
# Make predictions
y_pred = rf_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate classification report
class_report = classification_report(y_test, y_pred, target_names=data['class'].unique())
print("Classification Report:\n", class_report)

Accuracy: 0.8872832369942196
Classification Report:
               precision    recall  f1-score   support

       unacc       0.82      0.72      0.77        83
         acc       0.33      0.45      0.38        11
       vgood       0.94      1.00      0.96       235
        good       1.00      0.47      0.64        17

    accuracy                           0.89       346
   macro avg       0.77      0.66      0.69       346
weighted avg       0.89      0.89      0.88       346