In [15]:
import pandas as pd
df=pd.read_csv('Car_Evaluation.csv')

df.head()

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [16]:
columns=['Buying','maint','doors','persons','lug_boot','safety','class']
df.columns=columns
df.head()

  Buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [17]:
df_mod=pd.get_dummies(data=df,columns=columns[:-1],drop_first=True)
df_mod.head()

,class,Buying_low,Buying_med,Buying_vhigh,maint_low,maint_med,maint_vhigh,doors_3,doors_4,doors_5more,persons_4,persons_more,lug_boot_med,lug_boot_small,safety_low,safety_med
0,unacc,False,False,True,False,False,True,False,False,False,False,False,False,True,False,True
1,unacc,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False
2,unacc,False,False,True,False,False,True,False,False,False,False,False,True,False,True,False
3,unacc,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True
4,unacc,False,False,True,False,False,True,False,False,False,False,False,True,False,False,False

In [30]:

X=df_mod.drop('class',axis=1)
y=df_mod['class']
X.head()

,Buying_low,Buying_med,Buying_vhigh,maint_low,maint_med,maint_vhigh,doors_3,doors_4,doors_5more,persons_4,persons_more,lug_boot_med,lug_boot_small,safety_low,safety_med
0,False,False,True,False,False,True,False,False,False,False,False,False,True,False,True
1,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False
2,False,False,True,False,False,True,False,False,False,False,False,True,False,True,False
3,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True
4,False,False,True,False,False,True,False,False,False,False,False,True,False,False,False

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y)

In [32]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(random_state=42)

In [33]:
clf.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [39]:
from sklearn.metrics import accuracy_score, classification_report
y_pred=clf.predict(x_test)
accuracy=accuracy_score(y_pred,y_test)
print(f'accuracy is {accuracy*100:.2f}%')
report=classification_report(y_pred,y_test,target_names=df_mod['class'].unique())
print(report)

accuracy is 89.81%
              precision    recall  f1-score   support

       unacc       0.82      0.80      0.81       106
         acc       0.20      0.67      0.31         6
       vgood       0.99      0.94      0.96       312
        good       0.54      0.88      0.67         8

    accuracy                           0.90       432
   macro avg       0.64      0.82      0.69       432
weighted avg       0.93      0.90      0.91       432